version: '2'
networks:
  movie:
    driver: bridge

services: 
  wildfly:
    build: wildfly
    volumes:
      - ${WILDFLY_DEPLOYMENTS}:/opt/jboss/wildfly/standalone/deployments/:rw
      - ${WILDFLY_LOGS}:/opt/jboss/wildfly/standalone/log/:rw
    ports:
      - "8080:8080"
      - "8787:8787"
    networks:
      - movie