version: '2'
networks:
  movie:
    driver: bridge

services: 
  wildfly:
    build: wildfly
    volumes:
      - ${WILDFLY_DEPLOYMENTS}:/opt/jboss/wildfly/standalone/deployments/:rw
      - ${WILDFLY_LOGS}:/opt/jboss/wildfly/standalone/log/:rw
    ports:
      - "8080:8080"
      - "8787:8787"
    networks:
      - movie
    depends_on: 
      - mariadb
  
  mariadb:
    build: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks: 
      - movie
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/data